schedules:
  - task:
      type: lambda
      name: SendSMS
      handler: send_sms.handler
      environment:
        - msisdn: "+639399106689"
        - message: "Hello from AWS"
      cron:
        "cron(0 * * * ? *)"
  - task:
      type: lambda
      name: SendEmail
      handler: send_sms.handler
      environment:
        - msisdn: "+639399106689"
        - message: "Hello from AWS"
      cron:
        "cron(0/10 * * * ? *)"
  - task:
      type: fargate
      name: CreateReport
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
      command:
        - sh
        - -c
        - now=$(date) && echo "Hello there, the cuirrent date & time is $now" && sleep 30
      cron:
        "cron(0/1 * * * ? *)"
