msisdn:
  "+639399106689"

message:
  "Hello from AWS"

schedules:
  - task:
      type: lambda
      name: SendSMS
      handler: send_sms.handler
      environment:
        - msisdn: "+639399106689"
        - message: "Hello from AWS"
      cron:
        "cron(0 * * * ? *)"
  - task:
      type: fargate
      name: CreateReport
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
      command:
        - sh
        - -c
        - sleep 30 && date
      cron:
        "cron(0/1 * * * ? *)"
